services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./src:/usr/src/app/src
      - ./tsconfig.json:/usr/src/app/tsconfig.json
    env_file:
      - .env
    depends_on:
      - redis
      - chroma
    command: pnpm run dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
      - chroma
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./src:/usr/src/app/src
      - ./tsconfig.json:/usr/src/app/tsconfig.json
    command: pnpm run work
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  chroma:
    image: "chromadb/chroma:1.0.13.dev120"
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  chroma_data:
